locale = {
    'start': "Hi. I am a bot on the Claude neural network. It is faster than ChatGPT, and in some ways smarter. Write whatever you want, but the dialogs are recorded for debugging the bot.\n\n I advise you to join the chat about me: https://t.me/???.\n\nYou can open settings using /settings or see hint using /help\n\nPlease choose your language (can be changed later by /lang).",
    'about_string': """
Bot is created by 🇷🇺Russian coder Akim using Claude и Kandinsky 2.1. It can talk with you, answer question and illustrate its messages with pictures.
Bot is in early development phase. If bot refuses to do something, first press "Reset" or type /reset. If that doesn't work, it's either the fault of Claude API and Kandinskiy (they may be temporarily unavailable), or the bot is broken (most likely). In any case, write to ???.
Write to the creator of the bot: https://t.me/...

We, the developers of KSD, are not responsible for any statements, advice or recommendations given by our bot.

We created KSD solely for entertainment. 

Any statements by the KSD may be illegal, unethical or dangerous.

 Users must exercise common sense and not follow any advice that may be illegal or cause harm to them or others. We do not control or endorse content generated by KSD.""", 
    'donate_string': """
You can support bot developer. Big thanks for any support! P.S. better donate on YooMoney, commision is lower.
""",   
    'help_string': """
The bot can conduct a dialogue, answer questions, and also illustrate its answers with pictures. 

Here is the list of commands:

/lang - choose language
/csd - write a CSD to the bot (use with a request, you can use it in a private chat without a command)
/reset - start a new dialog (and delete the old one)
/dark - write to Dark CSD (with jailbreak)
/web - write to the Web-CSD (with Web access)
/natasha - write to the girl Natasha
/kitty - write to kitten Murchik
/csdimg - generate an image by prompt (if you don't have a clear prompt, it's better to ask "/csd draw...")
/randimg - generate a random image
/donate - support the bot and its developer
/help - shows this message
/about - information about the bot
/stats - bot statistics
/settings - settings
/getprompts - see available bots
/*bot ID* - write to any bot from the list (they also remember the dialogue separately)
""",
    'settings_string': """Available settings:

    Reply - when you reply to bot's message, it will activate.
    Picture - Characters like /linus will have profile pictures (only in private messages. In chats they will always have pictures).
    Nnumber of images generated by single /csdimg command: """,
    'reset': 'Dialogue context reset.',
    'reset2': 'Reset dialogue.',
    'wait': "Generating response...",
    'wait_pic': "Drawing...",
    'wait_web': "Searching...",
    'censored': "\n\n⚠️ Some images were censored. Sorry.",
    'nomore10': "\n\n⚠️ Can't send more than 10 images.",
    'failedgen_img': '\n\n⚠️ Couldn\'t generate images: ',
    'here_are_pics': ' Here are pics (wait for few seconds):',
    'failedgen_msg': 'ERROR: Failed to generate message. Please try again or reset your dialogue. \n',
    'setlang': '🇬🇧 Language changed to English.',
    'chooselang': 'Choose your language:',
    'nomore5': "ℹ️ Can\'t generate more than 5 images.",
    'noless1': 'ℹ️ Can\'t generate more than 5 images.',
    'prompt_loc': ' Answer in English language.',

}
