locale = {
    'start': "Hi. I am a bot on the Claude neural network. It is faster than ChatGPT, and in some ways smarter. Write whatever you want, but the dialogs are recorded for debugging the bot. We don't show them to the FSB)\n\n I advise you to go to the chat about me: https://t.me/???",
    'about_string': """
Bot is created by Akim using Claude и Kandinsky 2.1. It can talk with you, answer question and illustrate its messages with pictures.
Bot is in early development phase. If bot refuses to do something, first press "Reset" or type /reset. If that doesn't work, it's either the fault of Claude API and Kandinskiy (they may be temporarily unavailable), or the bot is broken (most likely). In any case, write to ???.
Write to the creator of the bot: https://t.me/???

We, the developers of KSD, are not responsible for any statements, advice or recommendations given by our bot.

We created KSD solely for entertainment. 

Any statements by the KSD may be illegal, unethical or dangerous.

 Users must exercise common sense and not follow any advice that may be illegal or cause harm to them or others. We do not control or endorse content generated by KSD.""", 
    'donate_string': """
Вы можете поддержать разработчика бота. Заранее большое спасибо за любую поддержку! P.S. лучше переводить на YooMoney, комиссия меньше.
""",   
    'help_string': """
The bot can conduct a dialogue, answer questions, and also illustrate its answers with pictures. 

Here is the list of commands:

/csd - write a CSD to the bot (use with a request, you can use it in a LAN without a command)
/reset - start a new dialog (and delete the old one)
/dark - write to Dark CSD
/gopnik - write to gopnik Kolyan
/natasha - write to the girl Natasha
/kitty - write to kitten Murchik
/csdimg - generate an image on request (if you don't have a clear request, it's better to ask "/csd draw...")
/randimg - generate a random image
/donate - support the bot and its developer
/help - shows this message
/about - information about the bot
/stats - bot statistics
/settings - settings
/getprompts - see available bots
/*bot ID* - write to any bot from the list (they also remember the dialogue separately)
""",
    'settings_string': """Available settings:

    Reply - когда вы отвечаете на сообщение бота, он будет отвечать вам.
    Picture - когда отвечает какой-то персонаж, будет показана его картинка (только в ЛС. В беседах картинка будет всегда).
    Картинок за одну генерацию с /csdimg: """,
    'reset': 'История диалога сброшена.',
    'reset2': 'Диалог сброшен.',
    'wait': "Генерирую ответ...",
    'censored': "\n\n⚠️ Некоторые изображения подверглись цензуре.",
    'nomore10': "\n\n⚠️ Невоможно отправить больше 10 изображений.",
    'failedgen_img': '\n\n⚠️ Не удалось сгененировать изображения: ',
    'here_are_pics': ' Вот картинки (подождите несколько секунд):',
    'failedgen_msg': 'ERROR: Не удалось сгенерировать сообщение. Попробуйте ещё раз или сбросьте диалог. \n',
    'setlang': '🇪🇸 Spanish isn\'t done yet.',
    'chooselang': 'Choose your language:',
    'nomore5': "ℹ️ Can\'t generate more than 5 images.",
    'noless1': 'ℹ️ Can\'t generate more than 5 images.',
    

}
